begin;
-- Seed legacy hardcoded events into the events table.
-- Idempotent: ON CONFLICT (slug) DO NOTHING.

insert into public.events (slug, kind, title, description, where_, starts_at, ends_at, status, address, online_url) values ('2026-jun-12-networking-happy-hour', 'CONNECT', 'Networking Happy Hour', 'Come get to know your fellow local UXRs! Light appetizers provided and pickleball courts available to rent.', 'Bouldin Acres', '2026-06-12T17:30:00-05:00', '2026-06-12T20:30:00-05:00', 'open', 'Bouldin Acres', NULL) on conflict (slug) do nothing;
insert into public.events (slug, kind, title, description, where_, starts_at, ends_at, status, address, online_url) values ('2025-oct-17-october-happy-hour', 'CONNECT', 'October Happy Hour', 'Join us for our next CONNECT event at 6 PM at Culinary Dropout!', 'Culinary Dropout, Austin', '2025-10-17T18:00:00-05:00', '2025-10-17T20:00:00-05:00', 'closed', 'Culinary Dropout, Austin', NULL) on conflict (slug) do nothing;
insert into public.events (slug, kind, title, description, where_, starts_at, ends_at, status, address, online_url) values ('2025-jul-15-what-happened-turning-lessons-from-the-past-into-wins', 'REFLECT', 'What Happened? Turning lessons from the past into wins', 'Grab your coffee and join us to share stories and discuss challenges related to research time-to-value.', 'Google Meet · Online', '2025-07-15T08:00:00-05:00', '2025-07-15T09:00:00-05:00', 'closed', NULL, 'Google Meet · Online') on conflict (slug) do nothing;
insert into public.events (slug, kind, title, description, where_, starts_at, ends_at, status, address, online_url) values ('2025-jun-06-atx-uxr-anniversary-celebration', 'CONNECT', 'ATX UXR Anniversary Celebration', 'We''re turning one, y''all!', 'Aviator Pizza & Drafthouse', '2025-06-06T17:30:00-05:00', '2025-06-06T19:30:00-05:00', 'closed', 'Aviator Pizza & Drafthouse', NULL) on conflict (slug) do nothing;
insert into public.events (slug, kind, title, description, where_, starts_at, ends_at, status, address, online_url) values ('2025-apr-24-back-to-the-future-of-ux', 'LEARN', 'Back to the Future of UX', 'Revisiting Greg Parrott & Dr. Jakob Nielsen on AI and UX in light of the AI revolution. Are our fears coming true?', 'Baylor Scott & White Cafe', '2025-04-24T17:30:00-05:00', '2025-04-24T19:30:00-05:00', 'closed', 'Baylor Scott & White Cafe', NULL) on conflict (slug) do nothing;
insert into public.events (slug, kind, title, description, where_, starts_at, ends_at, status, address, online_url) values ('2025-mar-11-atx-uxrs-at-sxsw', 'CONNECT', 'ATX UXRs at SXSW', 'Let''s get together during SXSW at the Hotel Van Zandt 4th-floor rooftop pool.', 'Hotel Van Zandt Rooftop', '2025-03-11T17:00:00-05:00', '2025-03-11T20:00:00-05:00', 'closed', 'Hotel Van Zandt Rooftop', NULL) on conflict (slug) do nothing;
insert into public.events (slug, kind, title, description, where_, starts_at, ends_at, status, address, online_url) values ('2025-feb-28-february-happy-hour', 'CONNECT', 'February Happy Hour', 'We can''t wait to see you at our next happy hour. Keep doing amazing things!', 'Yard House, The Domain', '2025-02-28T17:00:00-06:00', '2025-02-28T20:00:00-06:00', 'closed', 'Yard House, The Domain', NULL) on conflict (slug) do nothing;
commit;
